name: Site Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Bundler Cache
      uses: actions/cache@v1
      with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Use Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install dependencies
      run: yarn
    - name: Crawl MeFi
      run: node cli.js deleted blue
    - name: Install Gems
      working-directory: mefideleted-blog
      run: | 
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build site
      run: JEKYLL_ENV=production bundle exec jekyll build
      working-directory: mefideleted-blog
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mefideleted-blog/_site
